### ISSUE TITLE
Izveštaj o ostvarenim profitima banke po transakcijama u menjačnici (strana 120)

### ISSUE THREAD

**Issue by matejavasic8321rn** [RAF-SI-2023/Banka-4-Backend#135]
Opis:
Potrebno je dodati novi entitet za beleženje profita banke u menjačnici.

Zadaci:
- Dodavanje sledećih polja u entitet:
  - Transakcija: Referenca na transakciju korisnika
  - Provizija banke: Fiksna provizija banke
  - Kupovni kurs: Kurs po kojem banka kupuje valutu od korisnika
  - Prodajni kurs: Kurs po kojem banka prodaje valutu korisniku
  - Količina novca: Ukupan iznos valute koje korisnik menja
  - Ukupan profit transakcije: Profit od razlike kupovno i prodajnog kursa i provizije
  
Napomena:
Provizija, Kupovni kurs, Prodajni kurs, Količina novca, Datum se izvlače iz transakcije (nije ih neophodno ponovo beležiti ukoliko nije praktično u okviru dosadašnje implementacije).

Primer izračunavanja:
Ukupan profit: Računa se na sledeći način:
Ako pretpostavimo da je srednji kurs 117.50 RSD/EUR, razlika između prodajnog i srednjeg kursa je profit banke po jedinici valute.
Razlika po kursu:
117.50 RSD/EUR - 116 RSD/EUR = 1.50 RSD/EUR
Ukupan profit od razlike u kursu:
1.50 RSD/EUR x 100 EUR = 150 RSD
Kada se ovome doda fiksna provizija od 200 RSD, dobijamo:
150 RSD + 200 RSD = 350 RSD

**Comment by PetarStamenic** [comment]
odlicno uradjeno
