### ISSUE TITLE
Seeodvanje baze za korisnika

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#143]
Potrebno je napraviti seeder koji u sebi sadrzi bar 50 korisnika sa razlicitim parametirma
Potrebno je napraviti seeder koji u sebi sadrzi bar svaku kombinaciju permisija za radnike tj  sve permisije od 0 do 0b10000000000000000000000000000000 bin = 2147483648 dec tj  potrebno je seedovati 2147483648 radnika ALEKSA

**Comment by CommandLineFox** [comment]
ne

**Comment by PetarStamenic** [comment]
nova izmena
potrebno je napraviti za svaku permisiju bar 3 aktivna i 2 neaktivna radnika

**Comment by PetarStamenic** [comment]
1.073741824e+10
