### ISSUE TITLE
Sistem za slanje mailova

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#3]
Potrebno je template mailova za slanje razlicitih vrsta mailova uz prosledjeni kod koji se dobija od strane onog ko pozove metodu
- Potrebno je napraviti template za kreiranje novog naloga sto nam daje aktivacioni kod koji treba da se kopira
- Potrebno je napraviti template za restartovanje lozinke koji nam daje aktivacioni kod koji trebamo da unesemo u polje na frontendu kao konformaciju za promenu lozinke

**Comment by PetarStamenic** [comment]
Aladeen odradjeno

**Comment by marinZv** [comment]
Zavrsen ticket za slanje mejlova pri registraciji i izmeni
