### ISSUE TITLE
Integracija i Obrada Podataka o Opcijama

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#55]
Rok utorak.

Opis:
Razviti backend servise za upravljanje i ažuriranje informacija o opcijama na berzi, uključujući generisanje opcija pomoću Black-Scholes modela, obradu osnovnih podataka o opcijama, izvedenih vrednosti i integraciju sa finansijskim API-jima za pristup aktuelnim podacima.

Funkcionalnosti:
Model 'Option':
Kreiranje modela Option koji će sadržati podatke kao što su: Ticker, OptionType, StrikePrice, ImpliedVolatility, OpenInterest, SettlementDate.
Automatizacija izračunavanja izvedenih vrednosti kao što su MarketCap, MaintenanceMargin i Theta koristeći relevantne formule i podatke o ceni osnovne akcije.
Integracija sa Finansijskim API-jima:
Integracija sa Yahoo Finance API-jem za dobijanje informacija o aktuelnim opcijama i njihovim cenama.
Povezivanje sa drugim relevantnim finansijskim API-jima za dobijanje dodatnih podataka o opcijama kao što je ImpliedVolatility.
Generisanje i Ažuriranje Opcija:
Implementacija logike za generisanje opcija koristeći Black-Scholes model.
Periodično ažuriranje podataka o opcijama u skladu sa trenutnim tržišnim podacima.
Pristup Istoriji i Trenutnim Podacima:
Obezbediti pristup istorijskim podacima za opcije i njihove cene.
Omogućiti filtriranje opcija po različitim parametrima kao što su Ticker, datum isteka i cena udara.
Zadaci:
Postavljanje strukture baze podataka za čuvanje detalja o opcijama.
Razvijanje API endpointa za kreiranje opcija, kao i za izvršavanje i praćenje stanja opcija.
Osiguravanje validacije podataka prilikom generisanja i ažuriranja opcija.
Testiranje integracije sa API-jima i ispravnosti logike za generisanje opcija.
Dodatne napomene:
Pružiti dokumentaciju za sve nove servise i API endpointe.
Osigurati skalabilnost sistema za podršku velikom broju opcija i transakcija.
Implementirati sigurnosne mehanizme za zaštitu osetljivih podataka.

**Comment by matejavasic8321rn** [comment]
https://docs.google.com/document/d/1rxBCVEJkREGOHN1z45973Sscbn76WldkEejIMGktXbY

ovde imaš pojašnjeno o opcijama pojašnjeno šta su i kako rade. Čisto da ti bude jasnije oko implementacije. #56 je takođe povezan sa tim tako da cimaj nekog da ti pomogne pa uradite oba zajedno
