### ISSUE TITLE
Limit i Stop Order Funkcionalnost

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#57]
Rok utorak.

Opis:
Izgraditi backend logiku za obradu Limit i Stop Order porudžbina koje omogućavaju korisnicima da postave cenu po kojoj žele da kupe ili prodaju hartije, te da porudžbine budu izvršene samo ako tržišna cena dostigne te vrednosti.

Zadaci:
Kreiranje modela za Limit i Stop Order porudžbine.
Implementacija logike za čekanje na tržišnoj ceni koja odgovara Limit ili Stop vrednosti.
Razvoj servisa za ažuriranje statusa porudžbina na osnovu promena tržišnih cena.
Kreiranje API endpointa za postavljanje, ažuriranje i otkazivanje Limit i Stop Order-a.
Obezbeđivanje robusnih testova koji će potvrditi tačnost i pouzdanost porudžbina.

**Comment by matejavasic8321rn** [comment]
Mojom greškom ovde fali još jedan deo. 

Opis:
Razviti servis za obradu Market Order porudžbina koji će omogućiti korisnicima da izvrše kupovinu ili prodaju hartija odmah po najboljoj trenutno dostupnoj ceni na berzi. Servis mora da podrži različite tipove hartija i bude usklađen sa pravilima berze za izvršavanje ovih porudžbina.

Zadaci:

Kreiranje modela porudžbina za Market Order u skladu sa specifikacijama iz dokumenta.
Implementacija logike izračunavanja procenjene cene Market Order-a na osnovu Ask i Bid cena.
Integracija sa tržišnim API-jima za dobijanje trenutnih Ask i Bid vrednosti.
Razvoj funkcionalnosti za automatsko izvršavanje Market Order-a kada se uslovi podudaraju.
Testiranje servisa za Market Order kako bi se osiguralo pravilno izvršavanje u realnom vremenu.
