### ISSUE TITLE
JWT servis

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#6]
Potrebno je napraviti JWT servis
Potrebno napraviti sistem za passworde koji se zasniva na [salt and hash](https://en.wikipedia.org/wiki/Salt_(cryptography))
Potrebno je implemenitati servis koji generise kod i cuva ga u nekom entitetu Email , Aktivacioni kod , Long za vreme isteka
ovaj kod ce se slati na mail i prilikom registracije ili prilikom promene lozinke ce se slati nazad nasem servisu i treba ga uporediti sa ovim kodom u tabeli. kada se kod jednom upotrebi potrebno ga je obrisati iz tabele.
Potrebno je napraviti metode za generisanje koda kao i za proveru koda koja vraca boolean a prima email i kod
JWT mora sadrzati id korisnika i permisije ukoliko ima ukoliko nema permisije sadrzi 0
implementacija se mora fokusirati na sto vecu bezbednost

**Comment by marinZv** [comment]
Zavrsen issue za JWT servis

**Comment by PetarStamenic** [comment]
Aladeen odradjeno
