### ISSUE TITLE
Potrebno je implemenitrati REST kontroler za user servis

### ISSUE THREAD

**Issue by PetarStamenic** [RAF-SI-2023/Banka-4-Backend#7]
Oslanjajuci se na interface UserService i sistem permisija potrebno je implementirati REST kontroler i swager
Kontroler mora imati:
- dodavanje novog korisnika
- menjanje postojeceg korisnika  - ovde nije potrebno proveriti da li korisnik ima edit opciju ukoliko je on sam pokrenuo postupak menjanja
- registraciju postojeceg korisnika na internet aplikaciju
- uzimanje usera na osnovu email
- uzimanje usera na osnovu broja telefona
- uzimanje usera na osnovu username i password
- uzimanje usera na osnovu JMBG
- inicijacia slanja email uz pomoc mail servisa kada korisnik pokrene proces registracije
- inicijacija slanje mail uz pomoc mail servisa kada korinnik pokrene proces zaboravljene lozinke
- promenu lozinke kada uz pomoc stare lozinke u formatu email stara lozinka nova lozinka - ovde nije potrebno proveriti da li korisnik ima edit opciju ukoliko je on sam pokrenuo postupak menjanja
- promenu lozinke uz pomoc koda za zaboravljenu lozinku u formatu email kod nova lozinka  - ovde nije potrebno proveriti da li korisnik ima edit opciju ukoliko je on sam pokrenuo postupak menjanja

**Comment by marinZv** [comment]
Zavrsen issue za Rest kontroler

**Comment by PetarStamenic** [comment]
Aladeen odradjeno
